# Generated by Django 4.2.11 on 2024-04-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_data', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correct_answer',
        ),
    ]
